services:
  - type: web
    name: greenhouse-backend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: development
