services:
  - type: web
    name: greenhouse-backend
    env: node
    plan: free
    branch: main  # Asegura que el deploy siempre tome 'main'
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true  # (opcional, ya es default, pero lo aclara)
    envVars:
      - key: NODE_ENV
        value: production
