services:
  - type: web
    name: greenhouse-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    branch: main
    region: oregon
